CREATE OR REPLACE TRIGGER DEMO_ORDER_actualizar_total
AFTER UPDATE ON DEMO_ORDER_ITEMS
REFERENCING OLD as old NEW AS new
FOR EACH ROW
DECLARE
BEGIN
    UPDATE DEMO_ORDERS 
    SET ORDER_TOTAL = ORDER_TOTAL - (:old.UNIT_PRICE * :old.QUANTITY) + (:new.UNIT_PRICE * :new.QUANTITY) 
    WHERE DEMO_ORDERS.ORDER_ID =  :old.ORDER_ID;
END;

